version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - zip -r function.zip .

  post_build:
    commands:
      - aws s3 cp function.zip s3://$artifactBucket/nordpool-ifttt-lambd/
      - echo Build Phase Complete
      - aws lambda update-function-code --function-name nordpool-ifttt-lambda --s3-bucket $artifactBucket --s3-key  nordpool-ifttt-lambd/function.zip
artifacts:
  files:
      - function.zip
